catchments_id_field: 'catchment_id'
top_catchments_cutoff: 0.01
pca_level: 'facility'
split_pca_by: ['setting']
use_pca_for_clustering: false
versions:
  census: '20240905-072347-cce9be26'
  h3_setup: '20250509-230920-52b814f3'
  catchments: '20251027-191319-9cfa4656'
  splitting: '20251027-204900-49d78ac7'
  prepared_data: '2025-10-27'
  analysis: '2025-10-27-metro'
covariates:
  population_1km: "Population density"
  evi: "Enhanced vegetation index"
  tt_walking: "Travel time to healthcare (walking)"
  built_surface: "Density of built structures"
  highways: "Distance to major roads"
  precipitation: "Precipitation"
  temperature: "Yearly average temperature (Kelvin)"
  ntl: "Nighttime light intensity"
  log_population_1km: "Population density (log-transformed)"
  rwi: "Relative wealth index"
  distance_admarc: "Distance to ADMARC facilities"
  distance_border_posts: "Distance to border posts"
  distance_towns: "Distance to towns (population > 20k)"
  distance_borders: "Distance to national borders"
  cropland_carbon_loss: 'Carbon loss from cropland'
  landuse_hard_commodities: 'Land use: hard commodities'
  landuse_logging: 'Land use: logging'
  landuse_agriculture: 'Land use: agriculture'
  landuse_settlements: 'Land use: settlements and infrastructure'
  log_ntl: "Nighttime light intensity (log-transformed)"
  tt_motorized: "Travel time to healthcare (motorized)"
  altitude: "Altitude"
  cropland_n2o_loss: 'Nitrogen loss from cropland'
  evapotranspiration: 'Evapotranspiration'
  latitude: "Latitude"
  longitude: "Longitude"
  people_near_forest: 'Forest-proximate people'
pca_covariates:
  landuse_hard_commodities: 'Land use: hard commodities'
  landuse_agriculture: 'Land use: agriculture'
  landuse_settlements: 'Land use: settlements and infrastructure' # Maybe not
  log_population_1km: "Population density"
  rwi: "Relative wealth index"
  # landuse_logging: 'Land use: logging'
  # log_ntl: "Nighttime lights"
log_transformed: ['log_population_1km', 'log_ntl']
directories:
  repo:
    versioned: FALSE
    path: '~/repos/mwi.hiv.factors'
    files:
      config: 'config.yaml'
  h3_setup:
    versioned: TRUE
    path: '~/repos/respond-map-prep/archive/h3_setup'
    files:
      id_raster: 'artefacts/id_raster.tif'
      pop_raster: 'artefacts/population_raster.tif'
      h3_aggregation_table: 'artefacts/h3_aggregation_table.csv'
      h3_centers: 'artefacts/h3_centers.csv'
      h3_polys: 'artefacts/h3_boundaries.gpkg'
  global_shp:
    versioned: FALSE
    path: '/mnt/c//Users/Lenovo/OneDrive - Henry Spatial Analysis LLC/Clients/DHS/Sharing/Updated GAUL shapefile'
    files:
      adm0: 'g2015_2014_0.shp'
      adm1: 'g2015_2014_1.shp'
      adm2: 'g2015_2014_2.shp'
  catchments:
    versioned: TRUE
    path: '~/repos/respond-map-prep/archive/assign_catchments'
    files:
      gvh_catchments: 'artefacts/gvh_catchments.gpkg'
      gvh_meta: 'artefacts/h3_catchments.csv'
      facility_catchments: 'artefacts/facility_catchments.gpkg'
      facility_metadata: 'artefacts/facilities_cleaned.csv'
      admin_bounds: 'artefacts/mwi_areas_ta.geojson'
  splitting:
    versioned: TRUE
    path: '~/repos/respond-map-prep/archive/split_model_results'
    files:
      aggregated_results: 'artefacts/aggregate_summary_table.csv'
  raw_vectors:
    versioned: FALSE
    path: '/mnt/c/Users/Lenovo/Dropbox/RESPOND_Community Archetyping/Datasets/original_vector_data'
    files:
      admarc: 'LSMS_2019/admarc_locations.shp'
      border_posts: 'LSMS_2019/BorderPosts.shp'
      towns: 'LSMS_2019/Malawi_towns.shp'
      town_populations: 'LSMS_2019/CityPopulation_c2018.xls'
  raw_data:
    versioned: FALSE
    path: '/mnt/c/Users/Lenovo/Dropbox/RESPOND_Community Archetyping/Datasets/original_raster_data'
    files:
      rwi_raw: "mwi_relative_wealth_index.csv"
      rwi: "mwi_rwi.tif"
      distance_admarc: "distance_admarc.tif"
      distance_border_posts: "distance_border_posts.tif"
      distance_towns: "distance_towns_over_20k.tif"
      distance_borders: "distance_national_borders.tif"
      tt_motorized: "202001_Global_Motorized_Travel_Time_to_Healthcare_MWI.tif"
      tt_walking: "202001_Global_Walking_Only_Travel_Time_To_Healthcare_MWI.tif"
      altitude: "altitude.tif"
      built_surface: "mwi_built_S_GHS_U_wFGW_100m_v1_2024.tif"
      highways: "mwi_highway_dist_osm_2023_100m_v1.tif"
      precipitation: "mwi_ppt_2023_yravg_tc_100m_v1.tif"
      temperature: "mwi_tavg_2023_tlst_100m_v1.tif"
      ntl: "mwi_viirs_nvf_2023_100m_v1.tif"
      population_1km: "mwi_ppp_2020_1km_Aggregated.tif"
      log_ntl: "mwi_viirs_nvf_2023_100m_v1.tif"
      log_population_1km: "mwi_ppp_2020_1km_Aggregated.tif"
      cropland_carbon_loss: 'croplandc.tif'
      cropland_n2o_loss: 'croplandn2o.tif'
      evapotranspiration: 'FLDAS_Evap_tavg.tif'
      people_near_forest: 'fpp.tif'
      landuse_hard_commodities: 'hard_commodities.tif'
      landuse_logging: 'logging.tif'
      landuse_agriculture: 'permanent_agriculture.tif'
      landuse_settlements: 'settlements_infra.tif'
      latitude: 'latitude.tif'
      longitude: 'longitude.tif'
  raster_db:
    versioned: FALSE
    path: '~/temp_data/rr'
    files:
      evi: 'evi/evi_mean_1y_2021_00_00.tif'
  prepared_data:
    versioned: TRUE
    path: '/mnt/c/Users/Lenovo/Dropbox/RESPOND_Community Archetyping/Datasets/cleaned_data'
    files:
      id_raster: 'id_raster.tif'
      aggregation_table_facility: 'aggregation_table_facility.csv'
      aggregation_table_gvh: 'aggregation_table_gvh.csv'
      covariates_by_facility: 'covariates_by_facility.csv'
      covariates_by_gvh: 'covariates_by_gvh.csv'
      covariates_viz: "covariates_by_catchment.pdf"
      covariates_viz_top_catchments: "covariates_by_catchment_top_catchments.pdf"
      covariates_viz_no_metros: "covariates_by_catchment_no_metros.pdf"
      covariates_viz_by_district: "covariates_by_catchment_by_district.pdf"
  analysis:
    versioned: TRUE
    path: '/mnt/c/Users/Lenovo/Dropbox/RESPOND_Community Archetyping/Analysis'
    files:
      pca_groups: 'pca_groups.csv'
      pca_importance: "{pca_group}/pca_importance.png"
      pca_loadings_table: "{pca_group}/pca_loadings_table.csv"
      pca_loadings: "{pca_group}/pca_loadings.png"
      pca_loadings_pt2: "{pca_group}/pca_loadings_pt2.png"
      kmeans_wss: "{pca_group}/kmeans_wss.png"
      kmeans_detail_template: "{pca_group}/kmeans_detail_{k}_means.png"
      kmeans_map_template: "{pca_group}/kmeans_map_{k}_means.png"
      pca_kmeans_results: '{pca_group}/pca_kmeans_results.csv'
      pca_kmeans_summaries: '{pca_group}/pca_kmeans_covariate_summaries.csv'
